services:
  portainer:
    image: portainer/portainer-ee:lts@sha256:465c705cccfda51e0b5aeffbb67d36038ac07a8704aa58251c6ec544e46ec5f2
    container_name: portainer
    restart: always
    network_mode: bridge
    cgroup: host
    command:
      - --sslcert
      - /certs/zeus.crt
      - --sslkey
      - /certs/zeus.key
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # /var/lib/docker/volumes/portainer_data/_data
      - /opt/docker/rootca/zeus:/certs

volumes:
  portainer_data:
    external: true
