services:
  portainer:
    image: portainer/portainer-ee:lts@sha256:18750221de87f489fffc3d52a23799e9c6a83aab0f1a5337824c81e12bf552b5
    container_name: portainer
    restart: always
    network_mode: bridge
    cgroup: host
    command:
      - --tlscert
      - /certs/zeus.crt
      - --tlskey
      - /certs/zeus.key
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # /var/lib/docker/volumes/portainer_data/_data
      - /opt/docker/rootca/zeus:/certs

volumes:
  portainer_data:
    external: true
