services:
  portainer:
    image: portainer/portainer-ee:lts@sha256:00c8114f44e240b4aa14429d365c1fb05cf7cd163ab0601c084c7af6ce8d58e2
    container_name: portainer
    restart: always
    network_mode: bridge
    cgroup: host
    command:
      - --sslcert
      - /certs/zeus.crt
      - --sslkey
      - /certs/zeus.key
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # /var/lib/docker/volumes/portainer_data/_data
      - /opt/docker/rootca/zeus:/certs

volumes:
  portainer_data:
    external: true
